[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = "This project is a 48h hackaton, whose objective is to create an AI Agent that can interact with people on WhatsApp. It is developped by Henri d'ANDRIA, in the context of an interview."
authors = ["Henri d'ANDRIA <henri.dandria@institut-ia.com>"]
license = "Private"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
python-multipart = "^0.0.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
